package paint;

import paint.mvc.PaintView;

import javax.swing.*;
import java.awt.*;

public class PaintForm extends JFrame {
    private JPanel mainPanel;

    private JRadioButton rbtnPoint;
    private JRadioButton rbtnLine;
    private JRadioButton rbtnRectangle;
    private JRadioButton rbtnCircle;
    private JRadioButton rbtnSquare;
    private JRadioButton rbtnSelect;
    private JButton btnDelete;
    private JButton btnUpdate;
    private JButton btnClearAll;

    private JPanel paintPanel;
    private JButton btnOutlineColor;
    private JButton btnInsideColor;
    private PaintView paint;


    public PaintForm() {

        $$$setupUI$$$();
        paint = (PaintView) paintPanel;

        setSize(700, 700);
        setContentPane(mainPanel);
        setLocationRelativeTo(null);

    }

    public PaintView getPaint() {
        return paint;
    }

    public void setPaint(PaintView paint) {
        this.paint = paint;
    }


    public JPanel getPaintPanel() {
        return paintPanel;
    }

    public void setPaintPanel(JPanel paintPanel) {
        this.paintPanel = paintPanel;
    }


    public JRadioButton getRbtnLine() {
        return rbtnLine;
    }

    public void setRbtnLine(JRadioButton rbtnLine) {
        this.rbtnLine = rbtnLine;
    }

    public JRadioButton getRbtnRectangle() {
        return rbtnRectangle;
    }

    public void setRbtnRectangle(JRadioButton rbtnRectangle) {
        this.rbtnRectangle = rbtnRectangle;
    }

    public JRadioButton getRbtnCircle() {
        return rbtnCircle;
    }

    public void setRbtnCircle(JRadioButton rbtnCircle) {
        this.rbtnCircle = rbtnCircle;
    }

    public JRadioButton getRbtnSquare() {
        return rbtnSquare;
    }

    public void setRbtnSquare(JRadioButton rbtnSquare) {
        this.rbtnSquare = rbtnSquare;
    }

    public JRadioButton getRbtnSelect() {
        return rbtnSelect;
    }

    public void setRbtnSelect(JRadioButton rbtnSelect) {
        this.rbtnSelect = rbtnSelect;
    }

    public JRadioButton getRbtnPoint() {
        return rbtnPoint;
    }

    public void setRbtnPoint(JRadioButton rbtnPoint) {
        this.rbtnPoint = rbtnPoint;
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }

    public void setBtnDelete(JButton btnDelete) {
        this.btnDelete = btnDelete;
    }

    public JButton getBtnUpdate() {
        return btnUpdate;
    }

    public void setBtnUpdate(JButton btnUpdate) {
        this.btnUpdate = btnUpdate;
    }

    public JButton getBtnClearAll() {
        return btnClearAll;
    }

    public void setBtnClearAll(JButton btnClearAll) {
        this.btnClearAll = btnClearAll;
    }

    public JButton getBtnOutlineColor() {
        return btnOutlineColor;
    }

    public void setBtnOutlineColor(JButton btnOutlineColor) {
        this.btnOutlineColor = btnOutlineColor;
    }

    public JButton getBtnInsideColor() {
        return btnInsideColor;
    }

    public void setBtnInsideColor(JButton btnInsideColor) {
        this.btnInsideColor = btnInsideColor;
    }

    private void createUIComponents() {
        paintPanel = new PaintView();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(6, 7, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setBackground(new Color(-13671681));
        rbtnRectangle = new JRadioButton();
        rbtnRectangle.setBackground(new Color(-13671681));
        rbtnRectangle.setForeground(new Color(-1310730));
        rbtnRectangle.setText("Rectangle");
        mainPanel.add(rbtnRectangle, new com.intellij.uiDesigner.core.GridConstraints(0, 4, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rbtnCircle = new JRadioButton();
        rbtnCircle.setBackground(new Color(-13671681));
        rbtnCircle.setForeground(new Color(-1310730));
        rbtnCircle.setText("Circle");
        mainPanel.add(rbtnCircle, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rbtnSquare = new JRadioButton();
        rbtnSquare.setBackground(new Color(-13671681));
        rbtnSquare.setForeground(new Color(-1310730));
        rbtnSquare.setText("Square");
        mainPanel.add(rbtnSquare, new com.intellij.uiDesigner.core.GridConstraints(0, 3, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnUpdate = new JButton();
        btnUpdate.setBackground(new Color(-33641));
        btnUpdate.setForeground(new Color(-1310730));
        btnUpdate.setText("Update");
        mainPanel.add(btnUpdate, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnDelete = new JButton();
        btnDelete.setBackground(new Color(-33641));
        btnDelete.setForeground(new Color(-1310730));
        btnDelete.setText("Delete");
        mainPanel.add(btnDelete, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rbtnSelect = new JRadioButton();
        rbtnSelect.setBackground(new Color(-13671681));
        rbtnSelect.setForeground(new Color(-1310730));
        rbtnSelect.setText("Select");
        mainPanel.add(rbtnSelect, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rbtnLine = new JRadioButton();
        rbtnLine.setBackground(new Color(-13671681));
        rbtnLine.setForeground(new Color(-1310730));
        rbtnLine.setText("Line");
        mainPanel.add(rbtnLine, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnClearAll = new JButton();
        btnClearAll.setBackground(new Color(-33641));
        btnClearAll.setForeground(new Color(-1310730));
        btnClearAll.setText("Clear all");
        mainPanel.add(btnClearAll, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        paintPanel.setBackground(new Color(-1));
        mainPanel.add(paintPanel, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 4, 6, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        rbtnPoint = new JRadioButton();
        rbtnPoint.setBackground(new Color(-13671681));
        rbtnPoint.setForeground(new Color(-1310730));
        rbtnPoint.setText("Point");
        mainPanel.add(rbtnPoint, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnOutlineColor = new JButton();
        btnOutlineColor.setBackground(new Color(-16777216));
        btnOutlineColor.setForeground(new Color(-1310730));
        btnOutlineColor.setText("Outline Color");
        mainPanel.add(btnOutlineColor, new com.intellij.uiDesigner.core.GridConstraints(0, 5, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnInsideColor = new JButton();
        btnInsideColor.setBackground(new Color(-1));
        btnInsideColor.setForeground(new Color(-16777216));
        btnInsideColor.setText("Inside Color");
        mainPanel.add(btnInsideColor, new com.intellij.uiDesigner.core.GridConstraints(0, 6, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(rbtnRectangle);
        buttonGroup.add(rbtnCircle);
        buttonGroup.add(rbtnSquare);
        buttonGroup.add(rbtnSelect);
        buttonGroup.add(rbtnLine);
        buttonGroup.add(rbtnPoint);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
