package paint;

import paint.mvc.PaintView;

import javax.swing.*;
import java.awt.*;

public class PaintForm extends JFrame {
    private JPanel mainPanel;

    private JRadioButton rbtnPoint;
    private JRadioButton rbtnLine;
    private JRadioButton rbtnRectangle;
    private JRadioButton rbtnCircle;
    private JRadioButton rbtnSquare;
    private JRadioButton rbtnHexagon;

    private JRadioButton rbtnSelect;

    private JButton btnDelete;
    private JButton btnUpdate;
    private JButton btnClearAll;
    private JButton btnDeselectAll;

    private JPanel paintPanel;

    private JButton btnOutlineColor;
    private JButton btnInsideColor;

    private JButton btnUndo;
    private JButton btnRedo;

    private PaintView paint;

    private JScrollPane log;
    private JList<String> logTxt;

    private JButton btnSaveLog;
    private JButton btnImportLog;

    private JButton btnSaveImage;
    private JButton btnImportImage;

    private JButton btnToFront;
    private JButton btnToBack;
    private JButton btnBringToFront;
    private JButton btnBringToBack;

    private JButton btnDownArrow;
    private JButton btnUpArrow;

    DefaultListModel listModel = new DefaultListModel();


    public PaintForm() {

        $$$setupUI$$$();
        this.setTitle("Paint App");
        paint = (PaintView) paintPanel;

        setSize(1400, 1400);
        setContentPane(mainPanel);
        setLocationRelativeTo(null);

        log.setPreferredSize(new Dimension(250, 150));

        // logTxt = new JList<String>(listModel);
        logTxt.setModel(listModel);


    }


    public PaintView getPaint() {
        return paint;
    }

    public void setPaint(PaintView paint) {
        this.paint = paint;
    }

    public JButton getBtnToFront() {
        return btnToFront;
    }

    public JButton getBtnDeselectAll() {
        return btnDeselectAll;
    }

    public JButton getBtnToBack() {
        return btnToBack;
    }

    public JButton getBtnBringToFront() {
        return btnBringToFront;
    }

    public JButton getBtnBringToBack() {
        return btnBringToBack;
    }

    public JButton getBtnDownArrow() {
        return btnDownArrow;
    }

    public JButton getBtnUpArrow() {
        return btnUpArrow;
    }

    public JButton getBtnSaveLog() {
        return btnSaveLog;
    }

    public JButton getBtnImportLog() {
        return btnImportLog;
    }

    public JButton getBtnSaveImage() {
        return btnSaveImage;
    }

    public JButton getBtnImportImage() {
        return btnImportImage;
    }

    public JList<String> getLogTxt() {
        return logTxt;
    }

    public DefaultListModel getListModel() {
        return listModel;
    }

    public JButton getBtnUndo() {
        return btnUndo;
    }

    public JButton getBtnRedo() {
        return btnRedo;
    }

    public JRadioButton getRbtnLine() {
        return rbtnLine;
    }

    public JRadioButton getRbtnRectangle() {
        return rbtnRectangle;
    }

    public JRadioButton getRbtnCircle() {
        return rbtnCircle;
    }

    public JRadioButton getRbtnSquare() {
        return rbtnSquare;
    }

    public JRadioButton getRbtnHexagon() {
        return rbtnHexagon;
    }

    public JRadioButton getRbtnSelect() {
        return rbtnSelect;
    }

    public JRadioButton getRbtnPoint() {
        return rbtnPoint;
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }

    public JButton getBtnUpdate() {
        return btnUpdate;
    }

    public JButton getBtnClearAll() {
        return btnClearAll;
    }

    public JButton getBtnOutlineColor() {
        return btnOutlineColor;
    }

    public void setBtnOutlineColor(JButton btnOutlineColor) {
        this.btnOutlineColor = btnOutlineColor;
    }

    public JButton getBtnInsideColor() {
        return btnInsideColor;
    }

    public void setBtnInsideColor(JButton btnInsideColor) {
        this.btnInsideColor = btnInsideColor;
    }

    private void createUIComponents() {
        paintPanel = new PaintView();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(38, 14, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setBackground(new Color(-10331398));
        paintPanel.setBackground(new Color(-1));
        mainPanel.add(paintPanel, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 34, 12, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 300), null, 0, false));
        log = new JScrollPane();
        log.setBackground(new Color(-1));
        mainPanel.add(log, new com.intellij.uiDesigner.core.GridConstraints(36, 0, 2, 14, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        logTxt = new JList();
        logTxt.setBackground(new Color(-12832056));
        logTxt.setForeground(new Color(-16777216));
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        logTxt.setModel(defaultListModel1);
        log.setViewportView(logTxt);
        btnSaveImage = new JButton();
        btnSaveImage.setBackground(new Color(-12832056));
        btnSaveImage.setForeground(new Color(-1310730));
        btnSaveImage.setText("Save Image");
        mainPanel.add(btnSaveImage, new com.intellij.uiDesigner.core.GridConstraints(35, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnImportImage = new JButton();
        btnImportImage.setBackground(new Color(-12832056));
        btnImportImage.setForeground(new Color(-1310730));
        btnImportImage.setText("Import Image");
        mainPanel.add(btnImportImage, new com.intellij.uiDesigner.core.GridConstraints(35, 4, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnSaveLog = new JButton();
        btnSaveLog.setBackground(new Color(-12832056));
        btnSaveLog.setForeground(new Color(-1310730));
        btnSaveLog.setText("Save Log");
        mainPanel.add(btnSaveLog, new com.intellij.uiDesigner.core.GridConstraints(35, 8, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnImportLog = new JButton();
        btnImportLog.setBackground(new Color(-12832056));
        btnImportLog.setForeground(new Color(-1310730));
        btnImportLog.setText("Import Log");
        mainPanel.add(btnImportLog, new com.intellij.uiDesigner.core.GridConstraints(35, 9, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnInsideColor = new JButton();
        btnInsideColor.setBackground(new Color(-1));
        btnInsideColor.setForeground(new Color(-16777216));
        btnInsideColor.setText("Inside Color");
        mainPanel.add(btnInsideColor, new com.intellij.uiDesigner.core.GridConstraints(0, 13, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnOutlineColor = new JButton();
        btnOutlineColor.setBackground(new Color(-16777216));
        btnOutlineColor.setForeground(new Color(-1310730));
        btnOutlineColor.setText("Outline Color");
        mainPanel.add(btnOutlineColor, new com.intellij.uiDesigner.core.GridConstraints(0, 12, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rbtnHexagon = new JRadioButton();
        rbtnHexagon.setBackground(new Color(-10331398));
        rbtnHexagon.setForeground(new Color(-1310730));
        rbtnHexagon.setText("Hexagon");
        mainPanel.add(rbtnHexagon, new com.intellij.uiDesigner.core.GridConstraints(0, 9, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rbtnRectangle = new JRadioButton();
        rbtnRectangle.setBackground(new Color(-10331398));
        rbtnRectangle.setForeground(new Color(-1310730));
        rbtnRectangle.setText("Rectangle");
        mainPanel.add(rbtnRectangle, new com.intellij.uiDesigner.core.GridConstraints(0, 8, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rbtnSquare = new JRadioButton();
        rbtnSquare.setBackground(new Color(-10331398));
        rbtnSquare.setForeground(new Color(-1310730));
        rbtnSquare.setText("Square");
        mainPanel.add(rbtnSquare, new com.intellij.uiDesigner.core.GridConstraints(0, 7, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rbtnCircle = new JRadioButton();
        rbtnCircle.setBackground(new Color(-10331398));
        rbtnCircle.setForeground(new Color(-1310730));
        rbtnCircle.setText("Circle");
        mainPanel.add(rbtnCircle, new com.intellij.uiDesigner.core.GridConstraints(0, 6, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rbtnLine = new JRadioButton();
        rbtnLine.setBackground(new Color(-10331398));
        rbtnLine.setForeground(new Color(-1310730));
        rbtnLine.setText("Line");
        mainPanel.add(rbtnLine, new com.intellij.uiDesigner.core.GridConstraints(0, 5, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnUndo = new JButton();
        btnUndo.setBackground(new Color(-12832056));
        btnUndo.setForeground(new Color(-1));
        btnUndo.setText("Undo");
        mainPanel.add(btnUndo, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnRedo = new JButton();
        btnRedo.setBackground(new Color(-12832056));
        btnRedo.setForeground(new Color(-1));
        btnRedo.setText("Redo");
        mainPanel.add(btnRedo, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rbtnSelect = new JRadioButton();
        rbtnSelect.setBackground(new Color(-10331398));
        rbtnSelect.setForeground(new Color(-1310730));
        rbtnSelect.setText("Select");
        mainPanel.add(rbtnSelect, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rbtnPoint = new JRadioButton();
        rbtnPoint.setBackground(new Color(-10331398));
        rbtnPoint.setForeground(new Color(-1310730));
        rbtnPoint.setText("Point");
        mainPanel.add(rbtnPoint, new com.intellij.uiDesigner.core.GridConstraints(0, 4, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnDeselectAll = new JButton();
        btnDeselectAll.setBackground(new Color(-12832056));
        btnDeselectAll.setForeground(new Color(-1310730));
        btnDeselectAll.setText("Deselect All");
        mainPanel.add(btnDeselectAll, new com.intellij.uiDesigner.core.GridConstraints(26, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnClearAll = new JButton();
        btnClearAll.setBackground(new Color(-12832056));
        btnClearAll.setForeground(new Color(-1310730));
        btnClearAll.setText("Clear all");
        mainPanel.add(btnClearAll, new com.intellij.uiDesigner.core.GridConstraints(25, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnDelete = new JButton();
        btnDelete.setBackground(new Color(-12832056));
        btnDelete.setForeground(new Color(-1310730));
        btnDelete.setText("Delete");
        mainPanel.add(btnDelete, new com.intellij.uiDesigner.core.GridConstraints(11, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnBringToFront = new JButton();
        btnBringToFront.setBackground(new Color(-12832056));
        btnBringToFront.setForeground(new Color(-1310730));
        btnBringToFront.setText("Bring To Front");
        mainPanel.add(btnBringToFront, new com.intellij.uiDesigner.core.GridConstraints(13, 13, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnBringToBack = new JButton();
        btnBringToBack.setBackground(new Color(-12832056));
        btnBringToBack.setForeground(new Color(-1310730));
        btnBringToBack.setText("Bring To Back");
        mainPanel.add(btnBringToBack, new com.intellij.uiDesigner.core.GridConstraints(12, 13, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnToBack = new JButton();
        btnToBack.setBackground(new Color(-12832056));
        btnToBack.setForeground(new Color(-1310730));
        btnToBack.setText("To Back");
        mainPanel.add(btnToBack, new com.intellij.uiDesigner.core.GridConstraints(11, 13, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnToFront = new JButton();
        btnToFront.setBackground(new Color(-12832056));
        btnToFront.setForeground(new Color(-1310730));
        btnToFront.setText("To Front");
        mainPanel.add(btnToFront, new com.intellij.uiDesigner.core.GridConstraints(10, 13, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnUpdate = new JButton();
        btnUpdate.setBackground(new Color(-12832056));
        btnUpdate.setForeground(new Color(-1310730));
        btnUpdate.setText("Update");
        mainPanel.add(btnUpdate, new com.intellij.uiDesigner.core.GridConstraints(10, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnDownArrow = new JButton();
        btnDownArrow.setHorizontalAlignment(0);
        btnDownArrow.setIcon(new ImageIcon(getClass().getResource("/down-arrow.png")));
        btnDownArrow.setText("");
        mainPanel.add(btnDownArrow, new com.intellij.uiDesigner.core.GridConstraints(35, 13, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(rbtnRectangle);
        buttonGroup.add(rbtnCircle);
        buttonGroup.add(rbtnSquare);
        buttonGroup.add(rbtnSelect);
        buttonGroup.add(rbtnLine);
        buttonGroup.add(rbtnPoint);
        buttonGroup.add(rbtnHexagon);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
